project:
  type: website

website:
  title: "Igors Dubanevics"
  description: "PhD candidate in evolutionary biology at OIST."
  site-url: "https://igorsdub.github.io"
  repo-url: "https://github.com/igorsdub/igorsdub.github.io"
  search: false
  navbar:
    background: light
    collapse: false
    right:
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
      - href: blog.qmd
        text: Blog
      - href: personal.qmd
        text: Personal
  page-navigation: false
  page-footer:
    center: "&copy; <script>document.write(new Date().getFullYear())</script> Igors Dubanevics &middot; Inspired by [Griffin Chure](https://gchure.bio/) &amp; [Brian Hie](https://brianhie.com/bookshelf) &middot; [Website Source](https://github.com/igorsdub/igorsdub.github.io)"
  open-graph: true
  twitter-card: true

format:
  html:
    theme:
      - cosmo
      - custom.scss
    css: styles.css
    toc: false
    link-external-newwindow: true
    email-obfuscation: javascript
    include-in-header: "files/includes/_academic.qmd"
