project:
  type: website

website:
  title: "Igors Dubanevics"
  description: "PhD candidate in evolutionary biology at OIST."
  site-url: "https://igorsdub.github.io"
  repo-url: "https://github.com/igorsdub/igorsdub.github.io"
  navbar:
    background: light
    left:
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
      - href: blog.qmd
        text: Blog
      - href: beyond-lab.qmd
        text: Beyond Lab
    right:
      - icon: github
        href: "https://github.com/igorsdub/igorsdub.github.io"
        aria-label: "Website Source Repository"
        target: _blank
  page-navigation: false
  page-footer:
    left: "Igors Dubanevics &copy; <script>document.write(new Date().getFullYear())</script>"
    center: "Design inspired by [Griffin Chure](https://gchure.bio/) and [Brian Hie](https://brianhie.com/bookshelf). Built with [Quarto](https://quarto.org) via [Dr. Gang He's template](https://github.com/drganghe/quarto-academic-website-template)."
    right: "[Website Source](https://github.com/igorsdub/igorsdub.github.io)"
  open-graph: true
  twitter-card: true

format:
  html:
    theme:
      - cosmo
      - custom.scss
    css: styles.css
    toc: false
    link-external-newwindow: true
    email-obfuscation: javascript
    include-in-header: "files/includes/_academic.qmd"
